name: nix build
on:
  workflow_call:
    inputs:
      cache-key:
        required: true
        type: string
jobs:
  check_nix:
    name: Check nix build
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: system-features = nixos-test benchmark big-parallel kvm
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4
      - name: Build executable
        run: nix -L build
      - name: Build docker image
        run: nix build -L '.#packages.x86_64-linux.hsec-tools-image'
      - run: mkdir -p ~/.local/dockerImages
      - run: cp result ~/.local/dockerImages/hsec-tools
      - uses: actions/cache/save@v3
        with:
          key: ${{ inputs.cache-key }}
          path: ~/.local/dockerImages
      - name: upload executable
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        with:
          name: hsec-tools-${{ github.sha }}
          path: ~/.local/dockerImages
